/**
 * Shared enumerations used across the application.
 * These ensure consistency between client and server.
 */

/** Match format - determines number of players on the pitch */
export type MatchFormat = '5v5' | '7v7' | '9v9' | '11v11';

/** Match structure - how the match is divided */
export type MatchStructure = 'halves' | 'quarters';

/** Player positions */
export type Position = 'GK' | 'CB' | 'LB' | 'RB' | 'CM' | 'LM' | 'RM' | 'CF';

/** Position groups for development goal library */
export type PositionGroup = Position | 'all';

/** Preferred foot */
export type PreferredFoot = 'left' | 'right' | 'both';

/** Availability status for a fixture */
export type AvailabilityStatus = 'available' | 'unavailable' | 'unknown';

/** Fixture types */
export type FixtureType = 'match' | 'training' | 'friendly' | 'tournament';

/** Fixture status */
export type FixtureStatus = 'scheduled' | 'completed' | 'cancelled';

/** Match objective - influences team selection */
export type MatchObjective = 'development' | 'balanced' | 'competitive';

/** Home or away */
export type HomeAway = 'home' | 'away';

/** FA Four Corners - development categories */
export type DevelopmentCategory = 'technical' | 'tactical' | 'physical' | 'psychological';

/** Development goal status */
export type DevelopmentStatus = 'working_on_it' | 'improving' | 'achieved';

/** Coaching philosophy setting */
export type CoachingPhilosophy = 'development' | 'balanced' | 'competitive';

/** Policy categories */
export type PolicyCategory =
  | 'philosophy'
  | 'playing_time'
  | 'positions'
  | 'goalkeeper'
  | 'match_objective'
  | 'statistics'
  | 'recognition'
  | 'ai_behaviour';

/** Match event types */
export type MatchEventType = 'goal' | 'assist' | 'sub_on' | 'sub_off' | 'gk_start' | 'gk_end';

/** Match result */
export type MatchResult = 'win' | 'draw' | 'loss';

/** Substitution plan generated by */
export type GeneratedBy = 'engine' | 'ai' | 'coach';

/** Training session block types */
export type TrainingBlockType =
  | 'warm_up'
  | 'technical_drill'
  | 'tactical_drill'
  | 'small_sided_game'
  | 'match'
  | 'cool_down'
  | 'discussion';
